# Stage 1: Build app
FROM node:18 AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install --production

COPY . .

RUN npm run build

# Stage 2: Run app
FROM node:18

WORKDIR /app

COPY --from=builder /app ./

EXPOSE 1337

CMD ["npm", "start"]
